
set(GXZN_GXZN_CHRONO_DEFINITIONS)

if(GXZN_GXZN_CHRONO_DEFINITIONS_INIT)
	set(GXZN_GXZN_CHRONO_DEFINITIONS ${GXZN_GXZN_CHRONO_DEFINITIONS_INIT})
endif()

string(TOUPPER ${CMAKE_BUILD_TYPE} upper_build_type)
if(GXZN_GXZN_CHRONO_DEFINITIONS_${upper_build_type})
	list(APPEND GXZN_GXZN_CHRONO_DEFINITIONS ${GXZN_GXZN_CHRONO_DEFINITIONS_${upper_build_type}})
endif()
unset(upper_build_type)

if(GXZN_GXZN_CHRONO_SYSTEM)
	string(TOUPPER ${GXZN_GXZN_CHRONO_SYSTEM} upper_system)
	list(APPEND GXZN_GXZN_CHRONO_DEFINITIONS GXZN_GXZN_CHRONO_SYSTEM_NAME="${GXZN_GXZN_CHRONO_SYSTEM}")
	list(APPEND GXZN_GXZN_CHRONO_DEFINITIONS GXZN_GXZN_CHRONO_${upper_system}=1)
endif()

unset(__me_suffixes)
